version: '3.8'

services:
  # app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"  # Map container port 8080 to host port 8080
    # environment:
    #   - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/activity?allowPublicKeyRetrieval=true&useSSL=false
    #   - SPRING_DATASOURCE_USERNAME=root
    #   - SPRING_DATASOURCE_PASSWORD=rootpassword
    # depends_on:
    #   - mysql
    # networks:
    #   - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"  # Expose MySQL port to the host (optional)
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=activity_management
    volumes:
      - mysql-data:/var/lib/mysql  # Persist MySQL data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
