server:
  port: 8080
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - env
        - beans
        - httptrace
        - metrics
        - loggers
        - threaddump
        - heapdump  
      base-path: /actuator
      
spring:
  application:
    name: ACTIVITY-GROUP3
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/activity
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop # Change this if needed (create, create-drop, validate, none)
    show-sql: true

    web:
      pageable:
        size-parameter: size
        max-page-size: 100
        one-indexed-parameters: true
        page-parameter: page
      sort:
        sort-parameter: sort

  # sql:
  #   init:
  #     data-locations:
  #       - classpath:sql/init.sql
  #     mode: always


logging:
  level:
    org:
      springframework:
        web: DEBUG
        data: DEBUG
        security: DEBUG
    com:
      product:
        service: DEBUG
    hibernate:
      SQL: DEBUG
      type: TRACE

jwt:
  base64-secret: hl4gDqBxBgOSDWqBlvwFYQInjYRGAdS4lUT7Nf3Zk1nItoSQ9wSFDPU+kXHKcKUW/UKbpGv9bCsa9S/QsoFRHw==
  access_token-validity-in-seconds: 90000000
  refresh_token-validity-in-seconds: 100000000
