server:
  port: 8080
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - env
          - beans
          - httptrace
          - metrics
          - loggers
          - threaddump
          - heapdump
      base-path: /actuator

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:winnnguyen1905.game@gmail.com}
    password: ${MAIL_PASSWORD:your_app_password_here}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    test-connection: false
  application:
    name: ACTIVITY-GROUP3
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/activity
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    serialization:
      write-dates-as-timestamps: false
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop # Change this if needed (create, create-drop, validate, none)
    show-sql: false
    defer-datasource-initialization: true
  # flyway:
  #   enabled: true
  #   locations: classpath:db/migration
  #   baseline-on-migrate: false
  #   init-sqls: CREATE SCHEMA IF NOT EXISTS activity
  data:
    web:
      pageable:
        size-parameter: size
        max-page-size: 100
        one-indexed-parameters: true
        page-parameter: page
      sort:
        sort-parameter: sort
    # Redis Configuration for SocketIO Caching
    redis:
      # Redis server connection
      host: localhost
      port: 6379
      password: # Leave empty if no password
      database: 0
      timeout: 2000ms
      
      # Connection pool settings
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms
  # sql:
  #   init:
  #     data-locations:
  #       - classpath:sql/init.sql
  #     mode: always

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    syntax-highlight:
      activated: true
    doc-expansion: none

# SocketIO specific configuration
socket:
  host: 0.0.0.0
  port: 9092

# Redis cache configuration
cache:
  redis:
    # Default TTL for cache entries
    default-ttl: 3600s
    # Enable Redis cache statistics
    enable-statistics: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data: DEBUG
        security: DEBUG
      flywaydb: DEBUG
    com:
      product:
        service: DEBUG
    hibernate:
      SQL: DEBUG
      type: TRACE

jwt:
  base64-secret: hl4gDqBxBgOSDWqBlvwFYQInjYRGAdS4lUT7Nf3Zk1nItoSQ9wSFDPU+kXHKcKUW/UKbpGv9bCsa9S/QsoFRHw==
  access_token-validity-in-seconds: 90000000
  refresh_token-validity-in-seconds: 100000000

# Profile-specific configurations
---
spring:
  config:
    activate:
      on-profile: production
  data:
    redis:
      host: redis-production-host
      port: 6379
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
      
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: redis
      port: 6379
