# Redis Configuration Example
# 
# NOTE: This configuration has been moved to application.yaml
# This file is kept for reference only.
#
# The Redis, SocketIO, and cache configurations below have been 
# integrated into the main application.yaml file.

# Original Redis Configuration for SocketIO Caching:
# 
# spring:
#   data:
#     redis:
#       host: localhost
#       port: 6379
#       password: # Leave empty if no password
#       database: 0
#       timeout: 2000ms
#       lettuce:
#         pool:
#           max-active: 8
#           max-idle: 8
#           min-idle: 0
#           max-wait: -1ms
#         shutdown-timeout: 100ms
#
# socket:
#   host: 0.0.0.0
#   port: 9092
#
# cache:
#   redis:
#     default-ttl: 3600s
#     enable-statistics: true
#
# Profile configurations for production and docker are also 
# included in the main application.yaml file.
